"""
tests/test_agents/test_pipeline_tool_use_failed.py

When Groq returns a 400 tool_use_failed error (malformed function call syntax
generated by the model), the pipeline must catch it and retry with the plain
client instead of propagating the exception.
"""
import sys
import types
from unittest.mock import MagicMock, patch

import pytest

# Stub langchain_groq before any app import touches it
_lc_groq = types.ModuleType("langchain_groq")
_lc_groq.ChatGroq = MagicMock  # type: ignore[attr-defined]
sys.modules.setdefault("langchain_groq", _lc_groq)


def _make_pipeline():
    """Build a VoiceAgentPipeline with fully mocked LLM and TTS services."""
    from app.agents.pipeline import VoiceAgentPipeline

    llm_mock = MagicMock()
    llm_mock.model_name = "test-model"
    tts_mock = MagicMock()

    # tool_client raises tool_use_failed; plain client returns a valid reply
    from groq import BadRequestError
    from langchain_core.messages import AIMessage
    import httpx

    bad_request = BadRequestError(
        message="Failed to call a function.",
        response=MagicMock(
            status_code=400,
            headers={},
            spec=httpx.Response,
        ),
        body={"error": {"code": "tool_use_failed"}},
    )

    plain_ai_msg = AIMessage(content="Here are your decks.")

    llm_mock.tool_client.invoke.side_effect = bad_request
    llm_mock.client.invoke.return_value = plain_ai_msg
    llm_mock.generate_response_with_grammar.return_value = ("Here are your decks.", None)
    tts_mock.convert_text_to_speech.return_value = b"audio"

    return VoiceAgentPipeline(llm_service=llm_mock, tts_service=tts_mock), llm_mock


def test_tool_use_failed_falls_back_to_plain_client():
    pipeline, llm_mock = _make_pipeline()

    with patch("app.agents.intent._wants_flashcard_tools", return_value=True):
        result = pipeline.run(user_input="show me my decks", user_id="a1000000-0000-0000-0000-000000000001")

    assert result["response_text"] == "Here are your decks."
    llm_mock.client.invoke.assert_called_once()


def test_tool_use_failed_does_not_propagate_exception():
    pipeline, _ = _make_pipeline()

    with patch("app.agents.intent._wants_flashcard_tools", return_value=True):
        try:
            pipeline.run(user_input="show me my decks", user_id="a1000000-0000-0000-0000-000000000001")
        except Exception as exc:
            pytest.fail(f"Exception should not propagate to caller: {exc}")


def test_tool_use_failed_logs_warning(caplog):
    import logging
    pipeline, _ = _make_pipeline()

    with patch("app.agents.intent._wants_flashcard_tools", return_value=True):
        with caplog.at_level(logging.WARNING, logger="AI-Lab-Agent"):
            pipeline.run(user_input="show me my decks", user_id="a1000000-0000-0000-0000-000000000001")

    assert any("tool_use_failed" in r.message for r in caplog.records)
