global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "voice-agent-backend"
    static_configs:
      - targets: ["backend-agent-service.english-speaking-agent.svc.cluster.local:8000"]
    metrics_path: /metrics
