name: Multi-Sync (Upstream & GitLab)

on:
  push:
    branches:
      - '**'

jobs:
  sync-and-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config Git
        run: |
          git config --global user.name "abcdefya"
          git config --global user.email "anh.dothe47@gmail.com"

      - name: Sync to Upstream (GitHub)
        if: ${{ github.ref_name != 'main' }}
        env:
          UPSTREAM_TOKEN: ${{ secrets.UPSTREAM_TOKEN }}
        run: |
          git remote add upstream https://x-access-token:${UPSTREAM_TOKEN}@github.com/a20-ai-thuc-chien/A20-App-014.git
          git push upstream HEAD:${{ github.ref_name }} --force

      - name: Mirror to GitLab
        if: ${{ github.ref_name == 'main' }}
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab-vinai.duckdns.org/root/English-Speaking-Agent.git
          git push gitlab HEAD:${{ github.ref_name }} --force
